[package]
name = "copper"
version = "0.2.0"
authors = ["Fayçal Beghalia", "Salma Boubakkar", "Wilfrid Wagon-Zekou"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "1"
prettytable-rs = "^0.10"
